using Microsoft.JSInterop;

namespace SpawnDev.BlazorJS.JSObjects
{
    /// <summary>
    /// The WebGLTransformFeedback interface is part of the WebGL 2 API and enables transform feedback, which is the process of capturing primitives generated by vertex processing. It allows to preserve the post-transform rendering state of an object and resubmit this data multiple times.<br/>
    /// https://developer.mozilla.org/en-US/docs/Web/API/WebGLTransformFeedback
    /// </summary>
    public class WebGLTransformFeedback : WebGLObject
    {
        /// <inheritdoc/>
        public WebGLTransformFeedback(IJSInProcessObjectReference _ref) : base(_ref) { }
    }
}
