using Microsoft.JSInterop;

namespace SpawnDev.BlazorJS.JSObjects
{
    /// <summary>
    /// The TextTrack interface of the WebVTT API represents a text track associated with a media element.<br/>
    /// https://developer.mozilla.org/en-US/docs/Web/API/TextTrack
    /// </summary>
    public class TextTrack : MediaTrack
    {
        /// <inheritdoc/>
        public TextTrack(IJSInProcessObjectReference _ref) : base(_ref) { }
        /// <summary>
        /// A TextTrackCueList object listing the currently active set of text track cues. Track cues are active if the current playback position of the media is between the cues' start and end times. Thus, for displayed cues such as captions or subtitles, the active cues are currently being displayed.
        /// </summary>
        public TextTrackCueList ActiveCues => JSRef!.Get<TextTrackCueList>("activeCues");
        /// <summary>
        /// A TextTrackCueList which contains all of the track's cues.
        /// </summary>
        public TextTrackCueList Cues => JSRef!.Get<TextTrackCueList>("cues");
        /// <summary>
        /// A string which identifies the track, if it has one. If it doesn't have an ID, then this value is an empty string (""). If the TextTrack is associated with a &lt;track> element, then the track's ID matches the element's ID.
        /// </summary>
        public string Id => JSRef!.Get<string>("id");
        /// <summary>
        /// Returns a string which indicates the track's in-band metadata track dispatch type.
        /// </summary>
        public string InBandMetadataTrackDispatchType => JSRef!.Get<string>("inBandMetadataTrackDispatchType");
        /// <summary>
        /// Returns a string indicating what kind of text track the TextTrack describes. It must be one of the permitted values.
        /// </summary>
        public string Kind => JSRef!.Get<string>("kind");
        /// <summary>
        /// A human-readable string which contains the text track's label, if one is present; otherwise, this is an empty string (""), in which case a custom label may need to be generated by your code using other attributes of the track, if the track's label needs to be exposed to the user.
        /// </summary>
        public string Label => JSRef!.Get<string>("label");
        /// <summary>
        /// A string specifying the language in which the text track's contents is written. The value must be a valid BCP 47 language tag, for example "en-US" for United States English or "pt-BR" for Brazilian Portuguese.
        /// </summary>
        public string Language => JSRef!.Get<string>("language");
        /// <summary>
        /// A string specifying the track's current mode, which must be one of the permitted values. Changing this property's value changes the track's current mode to match. The default is disabled, unless the &lt;track> element's default boolean attribute is set to true — in which case the default mode is showing.
        /// </summary>
        public string Mode { get => JSRef!.Get<string>("mode"); set => JSRef!.Set("mode", value); }
        /// <summary>
        /// The SourceBuffer that created the track. Returns null if the track was not created by a SourceBuffer or the SourceBuffer has been removed from the MediaSource.sourceBuffers attribute of its parent media source.
        /// </summary>
        public SourceBuffer? SourceBuffer => JSRef!.Get<SourceBuffer?>("sourceBuffer");
        /// <summary>
        /// Adds a cue (specified as a TextTrackCue object) to the track's list of cues.
        /// </summary>
        /// <param name="cue"></param>
        public void AddCue(TextTrackCue cue) => JSRef!.CallVoid("addCue", cue);
        /// <summary>
        /// Removes a cue (specified as a TextTrackCue object) from the track's list of cues.
        /// </summary>
        /// <param name="cue"></param>
        public void RemoveCue(TextTrackCue cue) => JSRef!.CallVoid("removeCue", cue);
        /// <summary>
        /// Fired when cues are entered and exited. A given text cue appears when the cue is entered and disappears when the cue is exited. Also available via the oncuechange property.
        /// </summary>
        public ActionEvent<Event> OnCueChange { get => new ActionEvent<Event>("cuechange", AddEventListener, RemoveEventListener); set { } }
    }
}